### ISSUE TITLE
Split name of items

### ISSUE THREAD

**Issue by vmonteirobr** [flareteam/flare-game#773]
Hi guys,
To simplify the translation work, i suggest splitting the names of the items.
Then translating few words making possible to instantly translated the most of items names.

Type of Items  = Ring, Tunic
Material of Items = Letter, Iron
Class of Items = Sorcerer, Recon

In the future maybe implement a procedural generation of items and your names.
Thanks.

**Comment by dorkster** [comment]
Doing this would be nice (and likely required if we want procedural items), but it's not exactly straight-forward. Here are some of my thoughts on this:

----

Some languages might not have the adjectives and nouns in the same order. Our GetText implementation gives us no way to have translators define such order. So having it all as one string gives the translator flexibility in this regard. Maybe we could split the display of the adjectives completely, like so:

```
Shirt
Material: Wool
Class: Recon
```

Yet this could be too much clutter. Also, how would we define the short labels (i.e. loot on the ground)? Would the above example just show "Shirt"? I don't really like that.

----

It might not be wise to split the material. For example, some languages might use one word to describe something like "Wool Shirt". Maybe this is an unwarranted concern. Though I think it's fair to say that the item "Class" should definitely be its own thing.

**Comment by vmonteirobr** [comment]
I agree, did not realize these contradictions in my suggestion, you're right. 

Is possible to create a string rule to forming the item name, solving your first and last concern?
Then with this rule present in translation file are possible adjust order of words.

`Item Name Rule = %Type %Material %Class`

Unfortunately the items name count approximately 30% of game data translation.
Thanks

**Comment by clintbellanger** [comment]
Word order is one hurdle, but it doesn't stop there. This doesn't happen too much in English, but in many languages the adjectives for Type or Material may change depending on the base item. E.g. if the object is considered singular or plural, male or female, those all could give adjectives different endings or forms.

Where possible we translate whole phrases together (instead of in parts) to avoid these kinds of issues.

This kind of support would be necessary if we wanted the engine to make random loot in realtime. Example, the Diablo style of combining Prefix-Object-Suffix like "Sharp Axe of the Eagle". (IMO there's still advantages of having random item and map generation happen offline though, makes it so the engine doesn't enforce tools or styles.)

**Comment by vmonteirobr** [comment]
I agree, you're right. Thanks all for explanation. I will continue translation in regular form.

**Comment by Wuzzy2** [comment]
> For example, some languages might use one word to describe something like "Wool Shirt". Maybe this is an unwarranted concern.

This concern is absolutely warranted.

Do not adopt this suggestion.
DO NOT ADOPT IT. REPEAT: DON'T!

This will NOT simplify translations, it makes them worse by making some translations impossible.

You all show an English bias by just assuming you can just randomly chain together certain words to build new words in other languages. It doesn't work that way. 

Very simple example:

It seems seductive to break up “Leather Tunic” into “Leather” and “Tunic”. However, even in German it already falls apart. The correct translation would be “Ledertunika” for the full item, and “Leder” and “Tunika” for “Leather” and “Tunic”, respectively. If you would just mindlessly chain together “Leder” and “Tunika”, you get “LederTunika”, which is wrong.

It gets worse the more complex the item names become. In German, you can combine nouns to create new nouns, which can become arbitrarily long.
Also, each of the word components might have a different meaning and grammar depending on where in the word it appears, which affects translation.

“Experience Ring” currently is translated as “Erfahrungsring”. But “Experience” alone translates to “Erfahrung” (not “Erfahrungs”) and “Ring” to “Ring”. The “s” in “Erfahrungsring” is dictated by grammar. Think it of a letter that “glues” both words together. However, with other words, there might be other letters required, or none. It's a bit messy. Long story short: **There is no trivial method to randomly combine arbitrary words in German**. Instead, you always have to translate the full thing.

And that's just German. Other languages will probably be wildly different.

Yes, it is more work to translate each item name individually, but this is absolutely required. Because of the compex grammars in many languages, this is just irreducible complexity. A high amount of strings is not an excuse to break things.

The current method is “1 item = 1 string”, which is correct. This is super-simple and Always Works®. Don't fix what isn't broken, thank you very much.

> Where possible we translate whole phrases together (instead of in parts) to avoid these kinds of issues.

This is the correct way to do it.

I recommend to reject this issue.

**Comment by dorkster** [comment]
Yep, definitely going to stick to the current method.
