### ISSUE TITLE
Click holding behaviour

### ISSUE THREAD

**Issue by Simon-Charest** [flareteam/flare-game#786]
Issue: When clicking and holding unto an enemy, the character will keep on swinging / shooting. But when the enemy dies, the player must release the mouse button to be able to move again.

Possible solution: Killing an enemy should "release, click then hold" the button automatically (unless the player holds the Shift button). The character would start walking toward the pointer, without the need of releasing and clicking the mouse button again.

Reason: This would reduce the clunkiness when switching between the attacking and moving stances.

Note: this is the normal Diablo 1 behaviour.

**Comment by dorkster** [comment]
Pressing an attack key while moving will cause the player to stop moving and attack. So in your solution, we'd need to lock the attack button to keep the player moving. At which point, the player would then need to release the attack button if they want to start attacking again. Seems clunkier than what we already have.

The player can either move or attack, but not both at the same time. Attacking is always going to take priority, so it's hard to avoid needing to release the attack button if the player wants to move.

**Comment by Simon-Charest** [comment]
I'm using the "Diablo mode" where I move my character holding the left button, attack clicking and holding the left button over an enemy and cast spells clicking the right button.

What I meant is that, while I'm holding the left button, if I move my cursor over an enemy, my character will switch to attacking automatically. This is perfect. But once the enemy dies, I will need to release the mouse button and click again for my character to switch back to moving again. Otherwise, he will keep on attacking forever. This is the normal behaviour when holding the Shift button. But it should switch back to moving automatically toward the pointer, without the need to release the left click button.

I must admit that this is very specific to the "old Diablo 1 type" of controls I use while playing Flare.

**Comment by ate088** [comment]
Agreed with this. I am trying FLARE 1.08 and although it is a great improvement over the previous version, having to release the mouse button in order to stop attacking and start moving again makes the controls feel 'sticky'.

**Comment by ate088** [comment]
Is there any way to do something like, lock left mouse button to attack as long as there are enemies in melee range, revert to being movement button if no enemies are in melee range?

**Comment by dorkster** [comment]
@ate088 Did you play with Flare 1.08.21? If not, you were still using the old mouse movement scheme. Left mouse is no longer used for movement and instead behaves just like when using regular keyboard movement. Right mouse is used for movement, and it will trigger the secondary power when Shift is pressed as well.

I like the way it is now, where there is a clean line between attacking and movement. I think the only change I'd consider making is if the player is attacking and not pressing the movement button(s), they could stop attacking completely and begin moving by pressing the movement buttons(s). That's pretty much how it works now, but because the player is holding the attack button, the movement state gets interrupted.

**Comment by ate088** [comment]
Yes, the change is a bit of a hard sell for me personally. It means that, should I wish to spend most of my time with playing the game with only the mouse (only occasionally reaching for the keyboard to pop a potion or something), I now have one skill that is even less accessible than before.

Take a look at the Diablo II Postmortem on Gamasutra here: http://www.gamasutra.com/view/feature/131533/postmortem_blizzards_diablo_ii.php?page=2

quote: 
>  We strove to make the interface as transparent as possible. You want to open a door? Left-click on it. Want to move to a target location? Left-click on it. Want to attack a monster, pick up an item, or talk to a non-player character? Well, you get the idea. It's amazing how many games have different controls and key combination for all these actions when simpler is always better.

I guess ARPG players like myself take for granted the considerations and under-the-hood complexity needed to achieve such mechanical simplicity, but it is an interesting problem nonetheless. :)

**Comment by dorkster** [comment]
I've read that article before and I still don't entirely agree with Blizzard's decision on that control scheme. I mean, it's worked for them, but it kind of falls apart when the player wants to use the "one-holy-button" to do an action, but accidentally ends up triggering one of the many other actions. This could be because the player's aim was misplaced, or because the game's order of operation gave priority to one action over another. Blizzard's solution, like any solution, comes with its drawbacks. I know I've accidentally moved when trying to attack in Diablo. And Flare is not Diablo, so we have the opportunity to choose a different solution (and the drawbacks it brings).

For players that want to play purely with the mouse, they'll likely want to remap the other action bar items to the other available mouse buttons. Even on a 3-button mouse, binding a slot to middle mouse gives you two attacks. If the mouse has side buttons (or is one of those wacky MMO mice with a >10 buttons), that opens even more options that further mitigate losing a button for movement. Maybe I'm wrong, but I'd say that players that like playing games primarily with the mouse would invest in a mouse that has > 3 buttons.

**Comment by ate088** [comment]
IMO the most ideal would still be identical Diablo style movement/attacking, but thanks for considering our feedback :)

I don't disagree entirely with your reasoning, I have ran into the problem you mentioned with Diablo style control schemes, and I know many dedicated players remap their movement button to, like, '1' or something to mitigate that. My worry is that Diablo style movement has become such a basic 'quality-of-life' feature in Diablo-style games that players would be thrown in for a loop if they are confronted with something that looks like Diablo, and clearly takes inspiration from Diablo, but functions entirely differently. It's a fact that every other ARPG from Path of Exile, to Torchlight, to Grim Dawn follows the basic control scheme that the very first Diablo popularized.

True, it doesn't necessarily mean that FLARE-game needs to follow that, but I do think modders would love to have the option, you know?

**Comment by ate088** [comment]
Hmm, I'm not very good at considering all the possibilities, but one possible hitch is what if players want to run away. Would "release, click then hold" suffice? Or would you need to shift-click to override it?

And if I wanted precision, FLARE's current WASD controls are honestly better than the all other Diablo likes already. I mean, have you tried stutter-stepping with WASD in FLARE? It's great. No other ARPG to my knowledge provides this.

Why not keep things accessible with Diablo-style mouse movement, and have WASD movement be  something like ''expert mode" if you are going to have your other hand on the keyboard anyways?

**Comment by Simon-Charest** [comment]
Yes, release, click then hold would suffice to run, as long as you are not pointing over another enemy.

Yes, I've tried the basic Flare RPG controls and didn't like them. I would rather move and attack with the mouse and use extra items with the keyboard. I hate having to move my fingers all over the keyboard or having one hand over the other.

**Comment by dorkster** [comment]
@Simon-Charest My above suggestion would work pretty much how you describe. Diablo II almost worked like that, but only if the player starts moving with the right mouse before hovering over an enemy. I'd like the player to keep moving after if their initial action is right clicking on an enemy, and it sounds like that's what you want as well.

@ate088 As I mentioned, my above suggestion is very Diablo-like, with the exception that left mouse doesn't have similar move/attack behavior. Let's briefly review the left mouse behavior in D2: Left mouse moves the player, but doesn't break out if the player hovers over an enemy. If a player attacks with left click, they stop all actions once the enemy dies. Would you consider combined move/attack on left mouse essential to your wishes for Flare's mouse control scheme?

I personally don't like having multiple buttons for movement, rather having 1 mouse button to replace WASD. In Flare 1.08, left mouse was for movement, but right mouse behaved just like one of the numbered action slots. These are currently swapped since the right mouse button has less global duty, so there's less chance for action overlap. I'm okay with Diablo-like behavior on the movement button as an optional work-around for players that are strictly mouse-only, but only because there's no other way to access that power without using the keyboard.

**Comment by ate088** [comment]
Hmm so if I understand, what we're trying now is:

LMB - Interact/Attack/LMB assigned skill
RMB - Move OR RMB assigned skill depending on context

Is this correct?

**Comment by dorkster** [comment]
@ate088 Correct. LMB stays the same as it is when using WASD controls. RMB is the only thing that will potentially change.

**Comment by ate088** [comment]
So it is the same as 1.08.21, minus the need to press shift to use the LMB assigned skill? It sounds like it could work, I'm trying to visualize it right now...

**Comment by dorkster** [comment]
Minus the need to press shift to use the *RMB* assigned skill. The LMB skill can be used without needing shift.

**Comment by ate088** [comment]
What is the behavior if I assign let's say 'Blood Strike' to RMB, and click-and-hold on an enemy? After executing Blood Strike once, what happens next? 
a) keep executing Blood Strike until I release RMB
b) switch over to normal attack, or 
c) switch over to move, not execute again until I click RMB again

In the case of a), if I assign normal attack to RMB wouldn't that pretty much be the Diablo control scheme but with RMB and LMB reversed?

**Comment by ate088** [comment]
Okay...so if I click-and-hold RMB on a single enemy, in this scenario: 
1) it will execute Blood Strike until the enemy died
2) after that, if I keep holding RMB down, it will move my character to mouse point and 
3) the moment my mouse hovers over a new enemy it will use Blood Strike on that enemy OR
4)if the enemy is out of range of Blood Strike it will move into range, and then use Blood Strike?

If this is the case what is the drawback if I were to let's say swap LMB and RMB around in keybindings? Combat-wise it seems like doing this will already make things identical to Diablo (the only thing being that all non-combat functions like talking to npcs and shops would use the RMB instead of the LMB but let's put that aside for now)

**Comment by ate088** [comment]
Right, if we can swap the mouse move over then my ideal set up would be:

LMB: Interact/ Mouse Move OR LMB assigned skill( behaving the way you currently suggest the RMB behaves)
RMB: RMB assigned skill

and my suggested default keybindings when you first start the game would be:

LMB: Blank slot
RMB: Swing/Shoot/Channel

**Comment by dorkster** [comment]
So as of https://github.com/flareteam/flare-engine/commit/b27ad0119109846a80c358f5d085c8ce720d81b5, Flare now has two new settings to control mouse movement behavior:

- Swap mouse movement button
- Attack with mouse movement

The default engine setting for these is swap=off, attack=on. This gives Diablo-like controls on the left mouse button. For the behavior that was introduced in Flare 1.08.21, it would be swap=on, attack=off. I've been enjoying my time playing with both settings turned on. So hopefully, everyone that wants to use mouse controls will be able to find a configuration they like.

@ate088 I have no plans to change the actionbar based on controls scheme. The default actionbar should be suitable for all control schemes, and it's easy enough for players to change if it's not.

**Comment by ate088** [comment]
Nice! I won't be able to try it until at least the end of the month though, I'll be pulling some serious overtime at work till then. Thank you so much for addressing our concerns, looking forward to the next build!
