### ISSUE TITLE
Alpha Demo Issues

### ISSUE THREAD

**Issue by Simon-Charest** [flareteam/flare-game#788]
In the Alpha Demo, finished quests do not stay in the Quests Log.

Also, it seems that the last quest, the brother one, can be done over and over again, by killing the brothers, getting the keys, opening the chests and going back again to the brothers...

It seems that there is no ending to the game. You might consider adding a congratulations message from an NPC in the village.

**Comment by dorkster** [comment]
>In the Alpha Demo, finished quests do not stay in the Quests Log.

This is a post-1.0 feature, and would require the quests to be titled. The Alpha Demo is frozen and isn't going to receive any updates (besides critical bug fixes).

>Also, it seems that the last quest, the brother one, can be done over and over again, by killing the brothers, getting the keys, opening the chests and going back again to the brothers...

I believe this was intentional, as it was kind of "end-game content" when all we had was the Alpha Demo.

>It seems that there is no ending to the game. You might consider adding a congratulations message from an NPC in the village.

Again, no game data changes to the Alpha Demo will be made.

**Comment by Simon-Charest** [comment]
Alright... but! This could mean that the engine code vs the campaign scripting is possibly not perfectly seperated. Otherwise, it would be easy to upgrade the engine without affecting the campaign's compatibility. Worst case, there should be a campaign upgrading tool.

**Comment by Simon-Charest** [comment]
Oh okay. Thanks for the info.
