### ISSUE TITLE
Flatpak version crashes when speaking to skeleton at the start

### ISSUE THREAD

**Issue by Mister-Dolus** [flareteam/flare-game#790]
When pressing space or enter to speak to the fallen skeleton in the starting area, the game will crash on me in Manjaro i3. It will also say that Flare is already running when trying to restart the game. The tarball version from Itch.io does not seem to have this problem.

Terminal output:

[fooman@fooman-pc ~]$ flatpak run org.flarerpg.Flare
INFO: Custom data path: "/app/share/games/flare/"
INFO: Flare 1.09 (Linux)
INFO: Active mods: default, fantasycore (1.09), empyrean_campaign (1.09)
INFO: MessageEngine: Using language 'en'
INFO: InputState: No joysticks were found.
INFO: Using Render Device: SDLHardwareRenderDevice (hardware, SDL 2, x11)
INFO: RenderDevice: 1 display(s), using display 0 (1920x1080 @ 60hz)
INFO: RenderDevice: Internal render size is 640x480
INFO: RenderDevice: Window size is 640x480
INFO: RenderDevice: Fullscreen=0, Hardware surfaces=1, Vsync=1, Texture Filter=1
INFO: RenderDevice: Display DPI is 81.573685
INFO: SoundManager: Using SDLSoundManager (SDL2, pulseaudio)
INFO: GameStateCutscene: Loading cutscene 'cutscenes/intro.txt'
INFO: GameStateCutscene: No scenes defined in cutscene file cutscenes/intro.txt
INFO: RenderDevice: Internal render size is 640x600
INFO: RenderDevice: Window size changed to 939x1030
INFO: Map: Loading map 'maps/spawn.txt'
INFO: Map: Loading map 'maps/arrival.txt'
/usr/include/c++/8.2.0/bits/stl_vector.h:932: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = MenuTalker::Action; _Alloc = 
std::allocator<MenuTalker::Action>; std::vector<_Tp, _Alloc>::reference = MenuTalker::Action&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), 
true)' failed.
/app/bin/flare.sh: line 1:     4 Aborted                 (core dumped) flare --mods=fantasycore,empyrean_campaign --data-path=/app/share/games/flare

**Comment by dorkster** [comment]
Fixed in this commit: https://github.com/flareteam/flare-engine/commit/bfc0cb36893ac33bd54af7b868cea7c0d3f6eb2f

Explanation: `chooseDialogNode()` clears the "actions" vector, so accessing an element for `npc->checkMovement()` is invalid. However, the memory can still be there because the vector's reserved capacity is unchanged. Non-flatpak versions got lucky by allowing the access to this memory without doing the bounds check.

Anyways, thanks for catching this. I'll likely push another Flare release with this patch later this week, since this is pretty nasty.

**Comment by Mister-Dolus** [comment]
Thanks for taking care of this so quickly.
