### ISSUE TITLE
infinity chests bug

### ISSUE THREAD

**Issue by foozzi** [flareteam/flare-game#810]
https://www.youtube.com/watch?v=smcMAeZOMXM

**Comment by dorkster** [comment]
In the Empyrean campaign, it is intentional that chests can be looted more than once. To balance this, we try to place the chests far enough away from the map entrances so that the player can't quickly farm them.

The map in your video is one of the oldest, so it's likely that this design aspect wasn't considered at the time. I'll move that particular chest to the south side of the map, which is far from all the map entrances and will nudge the player towards the toughest enemy on the map (the level 2 goblin).
