### ISSUE TITLE
Improving skills in Empirean compaign can ruin the character playability irreversibly

### ISSUE THREAD

**Issue by Sturwandan** [flareteam/flare-game#835]
Suppose, you are playing as adept, and thus the fireball is your primary weapon. When you advance several levels, you can stop using "channel" altogether, because fireball does slightly more damage and has much better range, while your MP regen will be enough to sustain your mana. However, when you advance Fireball instead of developing a new skill, you increase its mana requirement by 50% (from 2 to 3) while the damage is increased only by 9% (120%/110%), which means that instead of upgrading your attack you make it worse than it was, since damage output per mana drain becomes smaller. And on levels below 15 the mana drain is the primary limiting factor of your spells.

The problem is that you cannot undo the upgrade, and game is automatically saved, and with "improved" fireball your character has to resort to ice bolts... But if you have "upgraded" them as well, then you simply have nothing to fight, but weak "Channel" attack. 

My suggestion is that upgrade of the skill should not increase the mana requirement or that upgraded skill should be a separate skill (though it will overflow the magic skill tab) and if you take upgraded fireball you don't lose access to original 2mp one.  For example, small fireball, medium fireball and big fireball could be all separate skills without [+] button.

As alternative, damage output of the fireball could be increased at least as much as mana requirements. For example, if you get mana drain increased from 2 to 3 (by 50%) then damage should be increased and become at least 165% of basic mental damage on level 2 (110%×(3/2)) and 220% on level 3 (110%×(4mp/2mp)). Then you will have same damage/mana rate as the fireball lvl1, but with much better fire density which will be ideal against bosses and other high hp enemies.

Perhaps, we can say that bigger fireball have better energy conservation and make lvl2 fireball deal 170% damage and lvl3 fireball deal 230% damage.

If we go by levels as separate skills route, then perhaps, big fireball can replace fire burst, as the fireball would explode on contact with an enemy or a wall and deal splash damage, and, then, the fire line will only take three slots in skills menu.

**Comment by Sturwandan** [comment]
We can also combine my ideas like that:
Small fireball  — same as regular fireball lvl1, but the icon and projectile can be changed to have smaller fireball picture. On high enough level you can spam it like a machine gun and keep your mana regenerated faster then it's spent. 
Medium fireball — same as small fireball, but deals more damage, requires more mana and has burn effect on enemy, similar to blood strike. We can reuse picture of existing fireball.
Big fireball — big fireball, enough to one shot most monsters, but with high mana requirement and having splash damage plus burn effect. Replaces old burn spell.
All fireballs can also be upgraded and then they will deal slightly more damage, but mana requirement stays the same.

Icicle — same as basic ice spell, can be spammed indefinitely if you got enough mana regen.
Ice bolt — improved icicle which can stop an enemy completely on distance, but with more mana drain.
Ice storm — splash damage to a group of enemies. The enemy who was hit directly cannot move at all for some time. 

Electric shock — same as existing spell.
Lightning — enemy hit by a lightning bolt.
Thunderstorm — multiple lightnings hit the designated area, damaging enemies. Perhaps it could be something with insane mana requirements and with the storm clearing a significant part of map. Though it probably cannot be cast inside a cave or a building. 

I think that, the mage class should have at least some epic spells which do a lot, but also cost a lot. For example, 40 mana stones plus 80 mana points, plus a scroll which you can only craft yourself can be used to cause an earthquake or some kind of magic storm or something and clear entire map?

**Comment by onpon4** [comment]
I wanna bump this issue because I think this is a balance problem in mage build. The math just doesn't add up for upgrading any of the mage attacks, damage increase is so small but it increases MP cost so much it makes them unusable unless you chug a whole lot of potions I guess. Also for the splash damage attacks it's already problematic that they're 3 times as expensive as projectile attack and inflict way less damage, meaning you lose more MP if there's less than like 5 enemies in one spot or something, though Thunderstrike is helped in this regard by the much higher crit chance.

I think damage increases for the magician attack upgrades should be way bigger, I don't agree that it needs to be as much as the MP cost increase, but it needs to be enough so that the faster speed of killing enemies is worth the higher MP drain.

Also it doesn't make sense to upgrade ice at all, you don't even get a damage increase and the extra slow time doesn't help if it's just to help with lightning damage. Maybe the ice upgrades should be something different, or maybe the same plus increased damage, I get that fire is supposed to have the gimmick of more damage but fire can just be made even stronger to keep that gimmick, I think that would be better than making ice upgrades basically useless.

The fact that you need to upgrade the missile spells to get the splash spell upgrades also hurts it I think, you realistically can only ever get to level 17 in most cases and I think level 20 is the max IIRC, so that means 16 skill points or maybe 19 if you do a whole lot of grinding, and so to upgrade any splash skill to level 5 it costs almost 2/3 of your skill points, meaning you have to forego either all the other attack types or the MP upgrade or the shield power, and so now you just have a super high MP draining attack with either no MP regen bonus or no supplementary other attacks or maybe both.

So I think:

* Fire attacks should do way more damage and also get much faster damage increases
* Ice and lightning attacks should get more damage as they level up, not enough to overtake equal level fire attacks but enough to justify bigger MP cost
* Splash magic attacks should be leveled up independently from missile attacks
* MP of splash attacks being so expensive compared to missile attacks should be reconsidered, they already do less damage so I think that would balance them enough on its own, maybe a slightly higher MP cost but not triple I think

🕷️

**Comment by dorkster** [comment]
I just pushed my balance changes that should resolve the concerns in this issue. Firstly, the curve for MP costs has been made more gradual, so the MP cost of upgrades should now be more in line with their power increases. Secondly, I've added a new item, the Tome of Second Chances. It can be purchased from Florin and used to reset the player's stat and power points.

For more details on the balance changes, see these commits:
- b58962250fe1a1d9b3ab327d1f2a3e517fcfd229
- e8edd3b18935497892cda4662d427d21281b3ce9
- e1a3da84a1ef4abf8543cbd80cf77ffcf7ec09b8
- dfbd34fac8a8148cb705e42f7a9b3295dca214a4
- 39cccf7ac14ed6b2848a2448bde6855c992ed1e3
- 3b1e2823228bad0b723099879f0b3266f7f2ff72
- f4bfb217290e0a95927080a7ec2e576cbb68c4ec
- 9530f29322da0d1c401700dad0575126f0f312dd
- 504a55028f122c8751b38b3162db20da4dc100eb
