### ISSUE TITLE
Considering moving to a different irc network

### ISSUE THREAD

**Issue by basxto** [flareteam/flare-game#836]
There is a new `irc.freegamedev.net`, `#opengameart` is also moving there.
And since the forum is hosted on opengameart, it might make sense to follow.

**Comment by dorkster** [comment]
I support this idea, although I haven't visited the existing channel in years. I just created `#flarerpg` on the freeegamedev.net server.

**Comment by McSinyx** [comment]
@basxto and @poVoq, do you have any idea how to contact the people behind irc.freegamedev.net?  It would be lovely if they can support Matrix bridging as well.

**Comment by poVoq** [comment]
I am one of the main freegamedev.net admins.

The problem is that running a proper Matrix bridge requires running a Matrix homeserver, which I have done in the past and will never do again (horrible stuff).

Our Matterbridge bot bridge could link to any Matrix room though, but usually Matrix users complain about that.

It also looks like it might be possible to use the official Matrix XMPP bridge to connect to the XMPP gateway I am currently in the process of setting up, but such double bridging is very fail prone especially with all the alpha quality software Matrix is famous for.

**Comment by McSinyx** [comment]
Thank you @poVoq, a bot bridge would be fine to a casual player like me (if @dorkster is OK with it of course).  I'm active in the Pinephone rooms which is bot-bridged between Matrix, IRC, Discord and Telegram and thus much more chaotic and yet I got used to it.

**Comment by poVoq** [comment]
If someone wants to create a matrix room for flarerpg I am happy to add the bot bridge to it. Just let me know here or on the IRC channel.

**Comment by McSinyx** [comment]
I've just created [#flarerpg:halogen.city](https://matrix.to/#flarerpg:halogen.city) (I'm `@cnx:halogen.city`).  I think we should wait until @dorkster confirms that it's OK to bridge.

**Comment by dorkster** [comment]
@McSinyx I'm fine with the Matrix bridge.

**Comment by poVoq** [comment]
@McSinyx that homeserver has been up for a while and works well? I am looking for a server to create the bot account on, and maybe this would be an option? I don't like automatically handling all the data to NewVector Ltd. just because the bot uses a matrix.org account and thus all the rooms get replicated on their servers.

**Comment by poVoq** [comment]
So apparently the now working XMPP gateway can also be used with the Matrix to XMPP bridge. Seems to work alright.
Use: xmpp:#flarerpg@irc.freegamedev.net?join to connect to the IRC channel via XMPP.
For matrix it should be something like: /join #xmpp_#flarerpg_irc.freegamedev.net:matrix.org (no guarantees that this double bridge will not break horribly).

**Comment by McSinyx** [comment]
Nice!  I suppose the room in halogen city is no longer needed and also this issue has been resolved.

**Comment by poVoq** [comment]
I guess, up to you if you think it is still worthwhile to have a dedicated matrix room. The holdup with the bot bridge was really only that I couldn't decide where to register the bot account (and that Matrix in general is low on my list of priorities).

**Comment by McSinyx** [comment]
> The holdup with the bot bridge was really only that I couldn't decide where to register the bot account

Halogen city has been around for a few years, at least that's what its citizens told me, Iodine (the admin) didn't surface when I asked in the server's hall.  I've only been to the city for a few weeks and so far it's performing quite well.  For the time being I'm aliasing `#xmpp_#flarerpg_irc.freegamedev.net:matrix.org` to `#flarerpg:halogen.city`.

**Comment by poVoq** [comment]
Ah, how does that work? Is it just some sort of address redirect?

**Comment by jasonkhanlar** [comment]
IRC Network Suggestion: https://libera.chat/

Note: If you haven't heard anything about Freenode/Libera situation, back around April 2021, there was a lot of drama/lying/abuse of user data/hostile takeover, and so many staff/users/projects abandoned Freenode, and Libera.chat became fairly popular as a result. https://hackaday.com/2021/05/20/freenode-debacle-prompts-staff-exodus-new-network/

But otherwise, any other IRC network should be fine to consider as well, but I just thought I'd suggest Libera too, since I didn't see anyone mention it.

**Comment by McSinyx** [comment]
FYI @jasonkhanlar the channel was moved to freegamedev.net as shown in the commit above your comment.  I think this issue can be closed now.

**Comment by poVoq** [comment]
@jasonkhanlar if you want to make (and moderate) a #flarerpg channel on libera.chat we can easily bot-bridge it via the Matterbridge we run for such purposes on irc.freegamedev.net.
