### ISSUE TITLE
FLARE Error: Could not find the 'default' mod

### ISSUE THREAD

**Issue by kneekoo** [flareteam/flare-game#929]
When trying to start `flare-linux64-v1.14.AppImage`, I get this error:

![FLARE Error main: Could not find the 'default' mod in the following locations](https://user-images.githubusercontent.com/566306/209493210-88749e2f-bea2-41ac-b1fb-e2672a47cc4e.png)

What worked and still works normally for me, is `flare-linux64-v1.13.04.AppImage`.

`~/.local/share/flare/mods` exists, it's empty, and it was created Oct 31st, 2022 - when I first tried the game. It has the same permissions as the `saves` directory, which holds my data from my v1.13.04 gameplay. Can the 'default' mod be manually created there to get v1.14 going?

My OS: Linux Mint 20.3 Cinnamon 64-bit

P.S. Happy Holidays, and Merry Christmas! :)

**Comment by dorkster** [comment]
I see. I get the same behavior with 1.14 vs 1.13.04.

The temp directory will probably change on each launch, but the mods folders should be in:

```
/tmp/.mount_flare-kH4hIX/usr/share/flare/mods/
```

You can then copy those folders to:

```
/home/nicu/.local/share/flare/mods/
```

I'll see if I can fix the AppImage.

**Comment by dorkster** [comment]
Looks like I accidentally deleted my AppRun executable from the build environment, so linuxdeployqt was just symlinking to the flare executable. I've uploaded a fixed AppImage to all the download locations (Github/Sourceforge/itch.io).

I would appreciate if you could verify that it works on your end. Make sure you delete mods that you copied to `~/.local/share/flare/mods/` so that it can use the mods inside the AppImage.

**Comment by kneekoo** [comment]
It works just great, thanks a lot! :)
